image:
  repository: registry.gitlab.factory.social.gouv.fr/socialgouv/emjpm/app
  tag: latest
  pullPolicy: Always
replicas: 1
labels: {}
host: emjpm.dev.fabrique.social.gouv.fr
# tlsSecretName: app-certificate
tlsEnabled: true
tlsSecretName: wildcard-crt
fullnameOverride: ''
nameOverride: ''
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
resources:
  limits:
    cpu: 500m
    memory: 768Mi
  requests:
    cpu: 10m
    memory: 512Mi
