exports.getConfiguration = (env) => ({
  azureAccountKey: env.AZURE_ACCOUNT_KEY,
  azureAccountName: env.AZURE_ACCOUNT_NAME,
  awsEnabled: env.AWS_ENABLED || false,
  awsAccessKey: env.AWS_ACCESS_KEY,
  awsSecretAccess: env.AWS_SECRET_ACCESS,
  awsHost: env.AWS_HOST || "storage-eb4.cegedim.cloud",
  awsPort: env.AWS_PORT || 443,
  awsProtocol: env.AWS_PROTOCOL || "https",
  awsContextPath: env.AWS_CONTEXT_PATH,
  awsEndpoint: env.AWS_ENDPOINT,
  awsRegion: env.AWS_REGION || "aws-global",
  awsOCMIBucket: env.AWS_OCMI_BUCKET || "my-bucket",
  jwtConfig: require("./jwt")(env),
  logRequests: env.LOG_REQUESTS === "false" ? false : true,
  ocmiFilePassword: env.OCMI_FILE_PASSWORD,
  ocmiSyncFileEnabled: env.OCMI_SYNC_FILE_ENABLED === "true" ? true : false,
  ocmiSyncFileLocal: env.OCMI_SYNC_FILE_LOCAL === "true" ? true : false,
  ocmiSyncFileLocalDirPath: env.OCMI_SYNC_FILE_LOCAL_DIR_PATH || ".data/ocmi",
  sentryEnvironment: env.SENTRY_ENV,
  sentryPublicDSN: env.SENTRY_PUBLIC_DSN,
  smtpFrom: env.SMTP_FROM,
  smtpHost: env.SMTP_HOST || "127.0.0.1",
  smtpPass: env.SMTP_PASS,
  smtpPort: env.SMTP_PORT || "25",
  smtpUser: env.SMTP_USER,
});
